# Generated by Django 3.1.1 on 2020-09-24 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_topbar'),
    ]

    operations = [
        migrations.AddField(
            model_name='topbar',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
