# Generated by Django 3.1.1 on 2020-09-24 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_topbar_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='topbar',
            name='description',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
