# Generated by Django 3.1.1 on 2020-09-24 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_topbar_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topbar',
            name='description',
        ),
    ]
