# Generated by Django 3.1.1 on 2020-09-24 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_remove_topbar_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(height_field=1200, upload_to='news/%y/%m/%d/', width_field=1200),
        ),
    ]
